api_key=your_api_key
api_base_url=http://localhost:9001/api
auth0_issuer=https://idchest.com/auth/realms/''
auth0_discovery_url=https://idchest.com/auth/realms/''/.well-known/openid-configuration
auth0_server_client_id=neo-sso
auth0_login_callback_uri=com.idchest.neo:/login-callback
auth0_logout_callback_uri=com.idchest.neo:/logout-callback